# Generated by Django 2.1.4 on 2019-01-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_tags',
            field=models.ManyToManyField(null=True, to='backend.Subtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='backend.Tag'),
        ),
    ]
