# Generated by Django 2.1.4 on 2019-03-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190118_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
