# Generated by Django 2.1.7 on 2019-04-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190317_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Like'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_obj', related_query_name='comment_obj', to='backend.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_obj', related_query_name='post_obj', to='backend.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Like'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_tags',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Subtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Tag'),
        ),
    ]
